djangoProject/urls.py
from django.contrib import admin
from django.db import router
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from core.views import render_home, render_form, ObrashenieViewSet
from djangoProject import settings
router = DefaultRouter()
router.register(r'obrashenie', ObrashenieViewSet)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('add/', render_form, name='render_add'),
    path('', render_home
         ),
    path('api/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.
class Problems(models.Model):
    class Meta:
        verbose_name='Проблема'
        verbose_name_plural='Проблемы'


    name=models.CharField("Наименование",max_length=255)
    def __str__(self):
        return self.name

class PolEnum(models.IntegerChoices):
    MALE = 1, 'Мужской'
    FEMALE = 2, 'Женский'


class Status(models.Model):
    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    name = models.CharField("Наименование", max_length=255)

    def __str__(self):
        return self.name

class Obrashenie(models.Model):
    class Meta:
        verbose_name='Обращение'
        verbose_name_plural='Обращения'

    data_vnesenia=models.DateTimeField("Дата внесения", auto_now_add=True)
    phone = models.CharField("Телефон", max_length=255)
    first_name = models.CharField("Фамилия", max_length=255)
    second_name = models.CharField("Имя", max_length=255)
    otchestvo = models.CharField("Отчество", max_length=255,null=True,blank=True)
    vozrast = models.IntegerField("Возраст",null=True,blank=True)
    pol = models.IntegerField("Пол",choices=PolEnum.choices,default=PolEnum.MALE)
    adress = models.CharField("Место жительства", max_length=255)
    opisanie = models.TextField("Описание проблемы",null=True,blank=True)
    status=models.ForeignKey(Status,verbose_name='Статус',on_delete=models.SET_NULL,null=True,blank=False,default=1)
    problems = models.ForeignKey(Problems, verbose_name='Проблемы', on_delete=models.SET_NULL, null=True, blank=False,default=1)

    def __str__(self):
        return f"{self.first_name} {self.second_name} {self.phone}"

core/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet

from core.models import Obrashenie, PolEnum, Status, Problems
from core.serializers import ObrashenieSerializer

# API - модели
class ObrashenieViewSet(ModelViewSet):
    queryset = Obrashenie.objects.all()
    serializer_class = ObrashenieSerializer
    http_method_names = ['post',]

class ObrashenieList(APIView):
    def get(self, request, format=None):
        snippets = Obrashenie.objects.all()
        serializer = ObrashenieSerializer(snippets, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = ObrashenieSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def render_home(request):
    list_obrashenii = []
    param_poiska = {}
    obrashenie=Obrashenie.objects.all()
    if request.GET.get('first_name'):
        param_poiska['first_name']=request.GET.get('first_name')
        obrashenie=obrashenie.filter(first_name__icontains=request.GET.get('first_name'))
    if request.GET.get('second_name'):
        param_poiska['second_name'] = request.GET.get('second_name')
        obrashenie=obrashenie.filter(second_name__icontains=request.GET.get('second_name'))
    if request.GET.get('otchestvo'):
        param_poiska['otchestvo'] = request.GET.get('otchestvo')
        obrashenie=obrashenie.filter(otchestvo__icontains=request.GET.get('otchestvo'))
    if request.GET.get('phone'):
        param_poiska['phone'] = request.GET.get('phone')
        obrashenie=obrashenie.filter(phone__icontains=request.GET.get('phone'))
    if request.GET.get('vozrast'):
        param_poiska['vozrast'] = request.GET.get('vozrast')
        obrashenie=obrashenie.filter(vozrast=request.GET.get('vozrast'))
    if request.GET.get('pol'):
        param_poiska['pol'] = int(request.GET.get('pol'))
        obrashenie=obrashenie.filter(pol=request.GET.get('pol'))
    if request.GET.get('adress'):
        param_poiska['adress'] = request.GET.get('adress')
        obrashenie=obrashenie.filter(adress__icontains=request.GET.get('adress'))
    if request.GET.get('problem'):
        param_poiska['problem'] = int(request.GET.get('problem'))
        obrashenie=obrashenie.filter(problems_id=request.GET.get('problem'))
    if request.GET.get('status'):
        param_poiska['status'] = int(request.GET.get('status'))
        obrashenie=obrashenie.filter(status_id=request.GET.get('status'))
    return render(
        request,
        'core/home.html', {'obrashenie': obrashenie,
                           'pol_list': PolEnum,
                           'status_list': Status.objects.all(),
                           'problem_list': Problems.objects.all(),
                          'param_poiska':param_poiska,
                           })
def render_form(request):
    return render(
        request,
        'core/form_add.html',
        {
            'pol_list':PolEnum,
            'status_list':Status.objects.all(),
            'problem_list':Problems.objects.all(),
        }
    )

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'core/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"><img class="logo mr-3" src="{% static 'core/logo.png'%}" alt=""> Горячая линия</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>
{% block content %} {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
<script src="{% static 'core/script.js' %}"></script>
<script src="https://yastatic.net/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

</body>

</html>

core/templates/core/form_add.html
{% extends 'core/base.html' %}
{% block content %}
    <form class="form-message">
        {% csrf_token %}
        <div class="container">
            <div class="row">

                <div class="col-12 col-md-4">
                    <label for="">Фамилия</label>
                    <input name="first_name" class="form-control" type="text" required>
                </div>
                <div class="col-12 col-md-4">
                    <label for="">Имя</label>
                    <input name="second_name" class="form-control" type="text" required>
                </div>
                <div class="col-12 col-md-4">
                    <label for="">Отчество</label>
                  <input name="otchestvo" class="form-control" type="text">
                </div>
               <div class="col-12">
                    <label for="">Номер телефона</label>
                    <input name="phone" class="form-control" type="text" required>
                </div>
                <div class="col-6">
                    <label for="">Возраст</label>
                    <input name="vozrast" class="form-control" type="text" required>
                </div>
                <div class="col-6">
                    <label for="">Пол</label>
                    <select name="pol" class="custom-select" id="inputGroupSelect01">

                        <option selected></option>
                        <option value="{{ pol_list.FEMALE }}">{{ pol_list.FEMALE.label }}</option>
                        <option value="{{ pol_list.MALE }}">{{ pol_list.MALE.label }}</option>

                    </select>


                </div>
                <div class="col-12">
                    <label for="">Адрес</label>
                    <input name="adress" class="form-control" type="text" required>
                </div>
                <div class="col-12">
                    <label for="">Проблема</label>
                    <select name="problem" class="form-control" id="">
                        {% for i in problem_list %}
                            <option value="{{ i.id }}">{{ i.name }} </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-12">
                    <label for="">Описание</label>
                    <textarea name="opisanie" class="form-control " id="FCT" rows="3"></textarea>
                </div>
                <div class="col-12">
                    <label for="">Статус</label>
                    <select name="status" class="form-control" id="">
                        {% for i in status_list %}
                            <option value="{{ i.id }}">{{ i.name }} </option>
                        {% endfor %}

                    </select>
                </div>

            </div>
            <button type="submit" class="btn btn-primary btn-lg btn-block mt-3">Отправить</button>
        </div>

    </form>








{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-3">
                <form action="">
                    <h3>Поиск</h3>
                    <div class="">
                        <label for="">Фамилия</label>
                        <input value="{{ param_poiska.first_name }}" name="first_name" class="form-control" type="text">
                    </div>
                    <div class="">
                        <label for="">Имя</label>
                        <input value="{{ param_poiska.second_name }}" name="second_name" class="form-control" type="text">
                    </div>
                    <div class="">
                        <label for="">Отчество</label>
                        <input value="{{ param_poiska.otchestvo }}" name="otchestvo" class="form-control" type="text">
                    </div>
                    <div class="">
                        <label for="">Номер телефона</label>
                        <input value="{{ param_poiska.phone }}" name="phone" class="form-control" type="text">
                    </div>
                    <div class="">
                        <label for="">Возраст</label>
                        <input value="{{ param_poiska.vozrast }}" name="vozrast" class="form-control" type="text">
                    </div>
                    <div class="">
                        <label for="">Пол</label>
                        <select  name="pol" class="custom-select" id="inputGroupSelect01">

                            <option></option>
                            <option {% if param_poiska.pol == pol_list.FEMALE %}selected{% endif %} value="{{ pol_list.FEMALE }}">{{ pol_list.FEMALE.label }}</option>
                            <option {% if param_poiska.pol == pol_list.MALE %}selected{% endif %} value="{{ pol_list.MALE }}">{{ pol_list.MALE.label }}</option>

                        </select>


                    </div>
                    <div class="">
                        <label for="">Адрес</label>
                        <input value="{{ param_poiska.adress }}" name="adress" class="form-control" type="text">
                    </div>
                    <div class="">
                        <label for="">Проблема</label>
                        <select  name="problem" class="form-control" id="">
                        <option value="">---</option>
                            {% for i in problem_list %}
                                <option {% if param_poiska.problem == i.id %}selected{% endif %} value="{{ i.id }}">{{ i.name }} </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="">
                        <label for="">Статус</label>
                        <select name="status" class="form-control" id="">
                            <option value="">---</option>
                            {% for i in status_list %}
                                <option {% if param_poiska.status == i.id %}selected{% endif %} value="{{ i.id }}">{{ i.name }} </option>
                            {% endfor %}

                        </select>
                    </div>
                    <button class="btn btn-primary btn-block mt-3" type="submit">
                        Поиск
                    </button>
                </form>
            </div>
            <div class="col-12 col-md-9">
                <table class="table">
                    <tr>
                        <th>
                            Телефон
                        </th>
                        <th>
                            ФИО
                        </th>
                        <th>
                            Адрес
                        </th>
                        <th>
                            Возраст
                        </th>
                        <th>
                            Пол
                        </th>
                        <th>
                            Описание
                        </th>
                        <th>
                            Статус
                        </th>
                        <th>
                            Проблема
                        </th>
                    </tr>
                    {% for i in obrashenie %}
                        <tr>
                            <td>
                                {{ i.phone }}
                            </td>
                            <td>
                                {{ i.first_name }} {{ i.second_name }} {{ i.otchestvo|default_if_none:'' }}
                            </td>
                            <td>
                                {{ i.adress }}
                            </td>
                            <td>
                                {{ i.vozrast|default_if_none:'' }}
                            </td>
                            <td>
                                {{ i.get_pol_display }}
                            </td>
                            <td>
                                {{ i.opisanie|truncatechars:50 }}
                            </td>
                            <td>
                                {{ i.status|default_if_none:'' }}
                            </td>
                            <td>
                                {{ i.problems }}
                            </td>

                        </tr>
                    {% endfor %}
                </table>
                <a href="{% url 'render_add' %}" class="btn btn-primary ">Добавить обращение</a>
            </div>
        </div>
    </div>


{% endblock %}